name: push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        run: |
          git clone https://github.com/ctfd/ctfd .
          git clone https://github.com/kazutoiris/ctfd-whale/ CTFd/plugins/CTFd-Whale
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: cjlu/ctfd
          tag: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        run: |
          git clone https://github.com/ctfd/ctfd .
          git clone https://github.com/kazutoiris/ctfd-whale/ CTFd/plugins/CTFd-Whale
      - name: Build and Publish Tag Docker image
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: ctfd # Provide only Docker image name
          dockerfile: Dockerfile
